name: Build+Test+Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Conjunto
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: conjunto

      - name: Checkout Delegation Program
        uses: actions/checkout@v4
        with:
          repository: magicblock-labs/delegation-program
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: delegation-program
          ref: v0.1.3

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'conjunto-build_test_lint-cache-bust-000'
          workspaces: |
            conjunto -> target
          cache-targets: true
          cache-all-crates: true
          cache-on-failure: true

      - name: Prebuild Conjunto Target Size
        run: du -h -d1 conjunto/target || true

      - name: Cargo Build
        run: make ci-build
        shell: bash
        working-directory: conjunto

      - name: Cargo Clippy Lint
        run: make ci-clippy
        shell: bash
        working-directory: conjunto

      - name: Cargo Test
        run: make ci-test
        shell: bash
        working-directory: conjunto

      - name: Postbuild Conjunto Target Size
        run: du -h -d1 conjunto/target
